"""Core module - base types, constants, and shared utilities."""
from betting_bot.core.config import Settings, get_settings
from betting_bot.core.constants import (
    DATA_SOURCE_INFO,
    DEFAULT_CV_FOLDS,
    DEFAULT_N_TRIALS_OPTUNA,
    DEFAULT_RANDOM_STATE,
    DEFAULT_TEST_SPLIT,
    DEFAULT_VALIDATION_SPLIT,
    KELLY_FRACTION_DEFAULT,
    MIN_POSITIVE_EV,
    ConfidenceLevel,
    DataSource,
    FeatureCategory,
    League,
    MatchResult,
    ModelName,
    PredictionType,
    RiskLevel,
)
from betting_bot.core.exceptions import (
    APIError,
    BettingBotError,
    ConfigurationError,
    DatabaseError,
    DataError,
    FeatureEngineeringError,
    ModelError,
    PredictionError,
)

__all__ = [
    "Settings",
    "get_settings",
    "BettingBotError",
    "DataError",
    "ModelError",
    "PredictionError",
    "ConfigurationError",
    "APIError",
    "DatabaseError",
    "FeatureEngineeringError",
    "League",
    "PredictionType",
    "ModelName",
    "MatchResult",
    "DataSource",
    "DATA_SOURCE_INFO",
    "ConfidenceLevel",
    "RiskLevel",
    "FeatureCategory",
    "DEFAULT_TEST_SPLIT",
    "DEFAULT_VALIDATION_SPLIT",
    "DEFAULT_CV_FOLDS",
    "DEFAULT_RANDOM_STATE",
    "DEFAULT_N_TRIALS_OPTUNA",
    "KELLY_FRACTION_DEFAULT",
    "MIN_POSITIVE_EV",
]
