"""initial_schema

Revision ID: 7cf2642cf797
Revises: 
Create Date: 2026-07-01 23:03:06.964561
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = '7cf2642cf797'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bookmaker',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('short_name', sa.String(length=20), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bookmaker_id'), 'bookmaker', ['id'], unique=False)
    op.create_index(op.f('ix_bookmaker_name'), 'bookmaker', ['name'], unique=True)
    op.create_table('feature_definition',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('source', sa.String(length=100), nullable=True),
    sa.Column('transformation', sa.String(length=200), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('version_added', sa.String(length=20), nullable=True),
    sa.Column('dependencies', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_definition_id'), 'feature_definition', ['id'], unique=False)
    op.create_index(op.f('ix_feature_definition_name'), 'feature_definition', ['name'], unique=True)
    op.create_table('league',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_code'), 'league', ['code'], unique=True)
    op.create_index(op.f('ix_league_id'), 'league', ['id'], unique=False)
    op.create_table('model_registry',
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('model_path', sa.String(length=500), nullable=False),
    sa.Column('model_type', sa.String(length=50), nullable=False),
    sa.Column('model_class', sa.String(length=200), nullable=False),
    sa.Column('training_date', sa.DateTime(), nullable=False),
    sa.Column('training_duration_seconds', sa.Float(), nullable=True),
    sa.Column('training_data_start', sa.DateTime(), nullable=True),
    sa.Column('training_data_end', sa.DateTime(), nullable=True),
    sa.Column('n_train_samples', sa.Integer(), nullable=True),
    sa.Column('n_features', sa.Integer(), nullable=True),
    sa.Column('target_variable', sa.String(length=50), nullable=False),
    sa.Column('is_classifier', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('hyperparameters', sa.JSON(), nullable=True),
    sa.Column('feature_importance', sa.JSON(), nullable=True),
    sa.Column('top_features', sa.JSON(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_registry_id'), 'model_registry', ['id'], unique=False)
    op.create_index(op.f('ix_model_registry_model_name'), 'model_registry', ['model_name'], unique=False)
    op.create_table('model_metric',
    sa.Column('model_id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=50), nullable=False),
    sa.Column('metric_value', sa.Float(), nullable=False),
    sa.Column('dataset_type', sa.String(length=20), nullable=False),
    sa.Column('fold', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['model_id'], ['model_registry.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_metric_id'), 'model_metric', ['id'], unique=False)
    op.create_index(op.f('ix_model_metric_model_id'), 'model_metric', ['model_id'], unique=False)
    op.create_table('season',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_season_id'), 'season', ['id'], unique=False)
    op.create_index(op.f('ix_season_league_id'), 'season', ['league_id'], unique=False)
    op.create_table('team',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('short_name', sa.String(length=50), nullable=True),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.Column('stadium', sa.String(length=300), nullable=True),
    sa.Column('founded_year', sa.Integer(), nullable=True),
    sa.Column('elo_rating', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_id'), 'team', ['id'], unique=False)
    op.create_index(op.f('ix_team_name'), 'team', ['name'], unique=False)
    op.create_table('match',
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('match_date', sa.DateTime(), nullable=False),
    sa.Column('kickoff_time', sa.String(length=20), nullable=True),
    sa.Column('round', sa.Integer(), nullable=True),
    sa.Column('venue', sa.String(length=300), nullable=True),
    sa.Column('home_goals', sa.Integer(), nullable=True),
    sa.Column('away_goals', sa.Integer(), nullable=True),
    sa.Column('home_goals_ht', sa.Integer(), nullable=True),
    sa.Column('away_goals_ht', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=1), nullable=True),
    sa.Column('is_finished', sa.Boolean(), nullable=False),
    sa.Column('is_postponed', sa.Boolean(), nullable=False),
    sa.Column('home_possession', sa.Float(), nullable=True),
    sa.Column('away_possession', sa.Float(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('away_shots_on_target', sa.Integer(), nullable=True),
    sa.Column('home_corners', sa.Integer(), nullable=True),
    sa.Column('away_corners', sa.Integer(), nullable=True),
    sa.Column('home_fouls', sa.Integer(), nullable=True),
    sa.Column('away_fouls', sa.Integer(), nullable=True),
    sa.Column('home_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('away_yellow_cards', sa.Integer(), nullable=True),
    sa.Column('home_red_cards', sa.Integer(), nullable=True),
    sa.Column('away_red_cards', sa.Integer(), nullable=True),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('home_xga', sa.Float(), nullable=True),
    sa.Column('away_xga', sa.Float(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['away_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['home_team_id'], ['team.id'], ),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_match_away_team_id'), 'match', ['away_team_id'], unique=False)
    op.create_index(op.f('ix_match_home_team_id'), 'match', ['home_team_id'], unique=False)
    op.create_index(op.f('ix_match_id'), 'match', ['id'], unique=False)
    op.create_index(op.f('ix_match_league_id'), 'match', ['league_id'], unique=False)
    op.create_index(op.f('ix_match_match_date'), 'match', ['match_date'], unique=False)
    op.create_index(op.f('ix_match_season_id'), 'match', ['season_id'], unique=False)
    op.create_table('player',
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('nationality', sa.String(length=100), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.Column('external_id', sa.String(length=100), nullable=True),
    sa.Column('is_injured', sa.Boolean(), nullable=False),
    sa.Column('is_suspended', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_id')
    )
    op.create_index(op.f('ix_player_id'), 'player', ['id'], unique=False)
    op.create_index(op.f('ix_player_name'), 'player', ['name'], unique=False)
    op.create_index(op.f('ix_player_team_id'), 'player', ['team_id'], unique=False)
    op.create_table('team_stats',
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('matches_played', sa.Integer(), nullable=False),
    sa.Column('wins', sa.Integer(), nullable=False),
    sa.Column('draws', sa.Integer(), nullable=False),
    sa.Column('losses', sa.Integer(), nullable=False),
    sa.Column('goals_for', sa.Integer(), nullable=False),
    sa.Column('goals_against', sa.Integer(), nullable=False),
    sa.Column('goal_difference', sa.Integer(), nullable=False),
    sa.Column('points', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('home_wins', sa.Integer(), nullable=False),
    sa.Column('home_draws', sa.Integer(), nullable=False),
    sa.Column('home_losses', sa.Integer(), nullable=False),
    sa.Column('home_goals_for', sa.Integer(), nullable=False),
    sa.Column('home_goals_against', sa.Integer(), nullable=False),
    sa.Column('away_wins', sa.Integer(), nullable=False),
    sa.Column('away_draws', sa.Integer(), nullable=False),
    sa.Column('away_losses', sa.Integer(), nullable=False),
    sa.Column('away_goals_for', sa.Integer(), nullable=False),
    sa.Column('away_goals_against', sa.Integer(), nullable=False),
    sa.Column('form_string', sa.String(length=10), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_stats_id'), 'team_stats', ['id'], unique=False)
    op.create_index(op.f('ix_team_stats_league_id'), 'team_stats', ['league_id'], unique=False)
    op.create_index(op.f('ix_team_stats_season_id'), 'team_stats', ['season_id'], unique=False)
    op.create_index(op.f('ix_team_stats_team_id'), 'team_stats', ['team_id'], unique=False)
    op.create_table('feature_store',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('home_form_last_5', sa.Float(), nullable=True),
    sa.Column('away_form_last_5', sa.Float(), nullable=True),
    sa.Column('home_form_last_10', sa.Float(), nullable=True),
    sa.Column('away_form_last_10', sa.Float(), nullable=True),
    sa.Column('home_goals_scored_avg_5', sa.Float(), nullable=True),
    sa.Column('home_goals_conceded_avg_5', sa.Float(), nullable=True),
    sa.Column('away_goals_scored_avg_5', sa.Float(), nullable=True),
    sa.Column('away_goals_conceded_avg_5', sa.Float(), nullable=True),
    sa.Column('home_goals_scored_avg_10', sa.Float(), nullable=True),
    sa.Column('home_goals_conceded_avg_10', sa.Float(), nullable=True),
    sa.Column('away_goals_scored_avg_10', sa.Float(), nullable=True),
    sa.Column('away_goals_conceded_avg_10', sa.Float(), nullable=True),
    sa.Column('home_xg_avg_5', sa.Float(), nullable=True),
    sa.Column('away_xg_avg_5', sa.Float(), nullable=True),
    sa.Column('home_xga_avg_5', sa.Float(), nullable=True),
    sa.Column('away_xga_avg_5', sa.Float(), nullable=True),
    sa.Column('home_xg_avg_10', sa.Float(), nullable=True),
    sa.Column('away_xg_avg_10', sa.Float(), nullable=True),
    sa.Column('home_xga_avg_10', sa.Float(), nullable=True),
    sa.Column('away_xga_avg_10', sa.Float(), nullable=True),
    sa.Column('home_elo', sa.Float(), nullable=True),
    sa.Column('away_elo', sa.Float(), nullable=True),
    sa.Column('elo_diff', sa.Float(), nullable=True),
    sa.Column('h2h_home_wins', sa.Integer(), nullable=True),
    sa.Column('h2h_draws', sa.Integer(), nullable=True),
    sa.Column('h2h_away_wins', sa.Integer(), nullable=True),
    sa.Column('h2h_home_goals_avg', sa.Float(), nullable=True),
    sa.Column('h2h_away_goals_avg', sa.Float(), nullable=True),
    sa.Column('h2h_matches_played', sa.Integer(), nullable=True),
    sa.Column('home_possession_avg_5', sa.Float(), nullable=True),
    sa.Column('away_possession_avg_5', sa.Float(), nullable=True),
    sa.Column('home_possession_avg_10', sa.Float(), nullable=True),
    sa.Column('away_possession_avg_10', sa.Float(), nullable=True),
    sa.Column('home_shots_avg_5', sa.Float(), nullable=True),
    sa.Column('away_shots_avg_5', sa.Float(), nullable=True),
    sa.Column('home_shots_on_target_avg_5', sa.Float(), nullable=True),
    sa.Column('away_shots_on_target_avg_5', sa.Float(), nullable=True),
    sa.Column('home_shots_avg_10', sa.Float(), nullable=True),
    sa.Column('away_shots_avg_10', sa.Float(), nullable=True),
    sa.Column('home_shots_on_target_avg_10', sa.Float(), nullable=True),
    sa.Column('away_shots_on_target_avg_10', sa.Float(), nullable=True),
    sa.Column('home_corners_avg_5', sa.Float(), nullable=True),
    sa.Column('away_corners_avg_5', sa.Float(), nullable=True),
    sa.Column('home_corners_avg_10', sa.Float(), nullable=True),
    sa.Column('away_corners_avg_10', sa.Float(), nullable=True),
    sa.Column('home_fouls_avg_5', sa.Float(), nullable=True),
    sa.Column('away_fouls_avg_5', sa.Float(), nullable=True),
    sa.Column('home_yellow_cards_avg_5', sa.Float(), nullable=True),
    sa.Column('away_yellow_cards_avg_5', sa.Float(), nullable=True),
    sa.Column('home_rest_days', sa.Float(), nullable=True),
    sa.Column('away_rest_days', sa.Float(), nullable=True),
    sa.Column('travel_distance', sa.Float(), nullable=True),
    sa.Column('home_league_position', sa.Integer(), nullable=True),
    sa.Column('away_league_position', sa.Integer(), nullable=True),
    sa.Column('home_points', sa.Integer(), nullable=True),
    sa.Column('away_points', sa.Integer(), nullable=True),
    sa.Column('points_diff', sa.Integer(), nullable=True),
    sa.Column('home_attack_strength', sa.Float(), nullable=True),
    sa.Column('away_attack_strength', sa.Float(), nullable=True),
    sa.Column('home_defense_strength', sa.Float(), nullable=True),
    sa.Column('away_defense_strength', sa.Float(), nullable=True),
    sa.Column('home_xg_diff', sa.Float(), nullable=True),
    sa.Column('away_xg_diff', sa.Float(), nullable=True),
    sa.Column('temperature', sa.Float(), nullable=True),
    sa.Column('humidity', sa.Float(), nullable=True),
    sa.Column('wind_speed', sa.Float(), nullable=True),
    sa.Column('weather_condition', sa.String(length=100), nullable=True),
    sa.Column('referee_id', sa.Integer(), nullable=True),
    sa.Column('referee_home_win_rate', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feature_store_feature_version'), 'feature_store', ['feature_version'], unique=False)
    op.create_index(op.f('ix_feature_store_id'), 'feature_store', ['id'], unique=False)
    op.create_index(op.f('ix_feature_store_match_id'), 'feature_store', ['match_id'], unique=False)
    op.create_table('odds',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('home_odds', sa.Float(), nullable=True),
    sa.Column('draw_odds', sa.Float(), nullable=True),
    sa.Column('away_odds', sa.Float(), nullable=True),
    sa.Column('over_2_5_odds', sa.Float(), nullable=True),
    sa.Column('under_2_5_odds', sa.Float(), nullable=True),
    sa.Column('over_1_5_odds', sa.Float(), nullable=True),
    sa.Column('under_1_5_odds', sa.Float(), nullable=True),
    sa.Column('over_3_5_odds', sa.Float(), nullable=True),
    sa.Column('under_3_5_odds', sa.Float(), nullable=True),
    sa.Column('btts_yes_odds', sa.Float(), nullable=True),
    sa.Column('btts_no_odds', sa.Float(), nullable=True),
    sa.Column('home_or_draw_odds', sa.Float(), nullable=True),
    sa.Column('home_or_away_odds', sa.Float(), nullable=True),
    sa.Column('draw_or_away_odds', sa.Float(), nullable=True),
    sa.Column('is_live', sa.Boolean(), nullable=False),
    sa.Column('is_opening', sa.Boolean(), nullable=False),
    sa.Column('is_closing', sa.Boolean(), nullable=False),
    sa.Column('odds_timestamp', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmaker.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_bookmaker_id'), 'odds', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_odds_id'), 'odds', ['id'], unique=False)
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=False)
    op.create_table('odds_history',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker_id', sa.Integer(), nullable=False),
    sa.Column('home_odds', sa.Float(), nullable=False),
    sa.Column('draw_odds', sa.Float(), nullable=False),
    sa.Column('away_odds', sa.Float(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['bookmaker_id'], ['bookmaker.id'], ),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_history_bookmaker_id'), 'odds_history', ['bookmaker_id'], unique=False)
    op.create_index(op.f('ix_odds_history_id'), 'odds_history', ['id'], unique=False)
    op.create_index(op.f('ix_odds_history_match_id'), 'odds_history', ['match_id'], unique=False)
    op.create_index(op.f('ix_odds_history_recorded_at'), 'odds_history', ['recorded_at'], unique=False)
    op.create_table('player_stats',
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('minutes_played', sa.Integer(), nullable=True),
    sa.Column('goals', sa.Integer(), nullable=False),
    sa.Column('assists', sa.Integer(), nullable=False),
    sa.Column('shots', sa.Integer(), nullable=True),
    sa.Column('shots_on_target', sa.Integer(), nullable=True),
    sa.Column('passes', sa.Integer(), nullable=True),
    sa.Column('pass_accuracy', sa.Float(), nullable=True),
    sa.Column('tackles', sa.Integer(), nullable=True),
    sa.Column('interceptions', sa.Integer(), nullable=True),
    sa.Column('fouls', sa.Integer(), nullable=True),
    sa.Column('yellow_cards', sa.Integer(), nullable=False),
    sa.Column('red_cards', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('is_starter', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['player.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_stats_id'), 'player_stats', ['id'], unique=False)
    op.create_index(op.f('ix_player_stats_player_id'), 'player_stats', ['player_id'], unique=False)
    op.create_index(op.f('ix_player_stats_season_id'), 'player_stats', ['season_id'], unique=False)
    op.create_table('prediction',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('feature_version', sa.String(length=20), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('over_2_5_probability', sa.Float(), nullable=True),
    sa.Column('under_2_5_probability', sa.Float(), nullable=True),
    sa.Column('btts_yes_probability', sa.Float(), nullable=True),
    sa.Column('btts_no_probability', sa.Float(), nullable=True),
    sa.Column('home_expected_goals', sa.Float(), nullable=True),
    sa.Column('away_expected_goals', sa.Float(), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('confidence_level', sa.String(length=20), nullable=True),
    sa.Column('model_confidence', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=20), nullable=True),
    sa.Column('prediction_date', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('model_version', sa.String(length=20), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_id'), 'prediction', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_match_id'), 'prediction', ['match_id'], unique=False)
    op.create_index(op.f('ix_prediction_model_name'), 'prediction', ['model_name'], unique=False)
    op.create_table('model_prediction',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('model_name', sa.String(length=100), nullable=False),
    sa.Column('home_win_probability', sa.Float(), nullable=True),
    sa.Column('draw_probability', sa.Float(), nullable=True),
    sa.Column('away_win_probability', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_prediction_id'), 'model_prediction', ['id'], unique=False)
    op.create_index(op.f('ix_model_prediction_match_id'), 'model_prediction', ['match_id'], unique=False)
    op.create_index(op.f('ix_model_prediction_prediction_id'), 'model_prediction', ['prediction_id'], unique=False)
    op.create_table('prediction_result',
    sa.Column('prediction_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('actual_home_goals', sa.Integer(), nullable=True),
    sa.Column('actual_away_goals', sa.Integer(), nullable=True),
    sa.Column('actual_result', sa.String(length=1), nullable=True),
    sa.Column('was_correct', sa.Boolean(), nullable=True),
    sa.Column('was_profitable', sa.Boolean(), nullable=True),
    sa.Column('roi', sa.Float(), nullable=True),
    sa.Column('profit_loss', sa.Float(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['prediction_id'], ['prediction.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_result_id'), 'prediction_result', ['id'], unique=False)
    op.create_index(op.f('ix_prediction_result_prediction_id'), 'prediction_result', ['prediction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_result_prediction_id'), table_name='prediction_result')
    op.drop_index(op.f('ix_prediction_result_id'), table_name='prediction_result')
    op.drop_table('prediction_result')
    op.drop_index(op.f('ix_model_prediction_prediction_id'), table_name='model_prediction')
    op.drop_index(op.f('ix_model_prediction_match_id'), table_name='model_prediction')
    op.drop_index(op.f('ix_model_prediction_id'), table_name='model_prediction')
    op.drop_table('model_prediction')
    op.drop_index(op.f('ix_prediction_model_name'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_match_id'), table_name='prediction')
    op.drop_index(op.f('ix_prediction_id'), table_name='prediction')
    op.drop_table('prediction')
    op.drop_index(op.f('ix_player_stats_season_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_player_id'), table_name='player_stats')
    op.drop_index(op.f('ix_player_stats_id'), table_name='player_stats')
    op.drop_table('player_stats')
    op.drop_index(op.f('ix_odds_history_recorded_at'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_match_id'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_id'), table_name='odds_history')
    op.drop_index(op.f('ix_odds_history_bookmaker_id'), table_name='odds_history')
    op.drop_table('odds_history')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_id'), table_name='odds')
    op.drop_index(op.f('ix_odds_bookmaker_id'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_feature_store_match_id'), table_name='feature_store')
    op.drop_index(op.f('ix_feature_store_id'), table_name='feature_store')
    op.drop_index(op.f('ix_feature_store_feature_version'), table_name='feature_store')
    op.drop_table('feature_store')
    op.drop_index(op.f('ix_team_stats_team_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_season_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_league_id'), table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_id'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index(op.f('ix_player_team_id'), table_name='player')
    op.drop_index(op.f('ix_player_name'), table_name='player')
    op.drop_index(op.f('ix_player_id'), table_name='player')
    op.drop_table('player')
    op.drop_index(op.f('ix_match_season_id'), table_name='match')
    op.drop_index(op.f('ix_match_match_date'), table_name='match')
    op.drop_index(op.f('ix_match_league_id'), table_name='match')
    op.drop_index(op.f('ix_match_id'), table_name='match')
    op.drop_index(op.f('ix_match_home_team_id'), table_name='match')
    op.drop_index(op.f('ix_match_away_team_id'), table_name='match')
    op.drop_table('match')
    op.drop_index(op.f('ix_team_name'), table_name='team')
    op.drop_index(op.f('ix_team_id'), table_name='team')
    op.drop_table('team')
    op.drop_index(op.f('ix_season_league_id'), table_name='season')
    op.drop_index(op.f('ix_season_id'), table_name='season')
    op.drop_table('season')
    op.drop_index(op.f('ix_model_metric_model_id'), table_name='model_metric')
    op.drop_index(op.f('ix_model_metric_id'), table_name='model_metric')
    op.drop_table('model_metric')
    op.drop_index(op.f('ix_model_registry_model_name'), table_name='model_registry')
    op.drop_index(op.f('ix_model_registry_id'), table_name='model_registry')
    op.drop_table('model_registry')
    op.drop_index(op.f('ix_league_id'), table_name='league')
    op.drop_index(op.f('ix_league_code'), table_name='league')
    op.drop_table('league')
    op.drop_index(op.f('ix_feature_definition_name'), table_name='feature_definition')
    op.drop_index(op.f('ix_feature_definition_id'), table_name='feature_definition')
    op.drop_table('feature_definition')
    op.drop_index(op.f('ix_bookmaker_name'), table_name='bookmaker')
    op.drop_index(op.f('ix_bookmaker_id'), table_name='bookmaker')
    op.drop_table('bookmaker')
    # ### end Alembic commands ###
